version: "3.7"

volumes:
  prometheus_data: {}

services:
  prometheus:
    image: prom/prometheus:v2.1.0
    container_name: prometheus
    hostname: prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yaml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
    ports:
      - "9090:9090"

  sendgrid_exporter:
    # image:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9154:9154"
    healthcheck:
      test: curl -s https://localhost:9154/-/healthy >/dev/null; if [[ $$? == 52 ]]; then echo 0; else echo 1; fi
      interval: 30s
      timeout: 5s
      retries: 5
    command: ""
    environment:
      DISABLE_EXPORTER_METRICS: "true"
      SENDGRID_API_KEY: ${SENDGRID_API_KEY}
      SENDGRID_USER_NAME: ${SENDGRID_USER_NAME}
