apiVersion: v1
kind: Service
metadata:
  name: {{ include "sendgrid_exporter.fullname" . }}
  labels:
    {{- include "sendgrid_exporter.labels" . | nindent 4 }}
  {{- with .Values.serviceAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "sendgrid_exporter.selectorLabels" . | nindent 4 }}
