global:
  scrape_interval:     60s
  evaluation_interval: 60s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets:
          -  prometheus:9090
          -  sendgrid_exporter:9154
